# Usa la imagen oficial de MySQL
FROM mysql:8.0.22

# Establece variables de entorno (opcional, pero mejor en docker-compose.yml)
ENV MYSQL_ROOT_PASSWORD parcial1*
ENV MYSQL_DATABASE db2_parcial1
ENV MYSQL_USER parcial1
ENV MYSQL_PASSWORD parcial1*

# Expone el puerto de MySQL
EXPOSE 3306
